name: lifequest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  lottie: ^3.3.3
  rive: ^0.14.7
  confetti: ^0.8.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo/app_icon.png"
  web:
    generate: true
    image_path: "assets/logo/app_icon.png"
